### ISSUE TITLE
fatal error: 'proj.h' file not found

### ISSUE THREAD

**Issue by svevang** [georust/proj-sys#3]
I'm getting an error while building:

```
   Compiling proj-sys v0.6.1 (file:///private/tmp/proj-sys)
error: failed to run custom build command for `proj-sys v0.6.1 (file:///private/tmp/proj-sys)`
process didn't exit successfully: `/private/tmp/proj-sys/target/debug/build/proj-sys-de8be0349baaa23b/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=proj

--- stderr
wrapper.h:1:10: fatal error: 'proj.h' file not found
wrapper.h:1:10: fatal error: 'proj.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Rather than juggling system proj.4 versions and header files, would it make sense to directly build and link proj.4 doing something like in [libgit2-sys](https://github.com/alexcrichton/git2-rs/blob/master/libgit2-sys/build.rs)?

**Comment by urschrei** [comment]
Possibly, but I've had terrible luck with attempts to include external libs cross-platform, because we'd realistically need to set it up for Linux, macOS, and Windows. What platform are you on, and what version of PROJ did you install?

**Comment by svevang** [comment]
MacOS with 4.9.3 installed via brew. After upgrading to 5.0.0, proj-sys builds and the proj-rust test suite runs. 

Using the git2-rs crate as an example, I went a little ways down the path of using the cmake crate to build proj.4. https://github.com/svevang/proj-sys/commits?author=svevang
Problems: First, cmake uses an rpath lookup scheme, which cuts against wrapping a library in the cargo package system. Rust discourages relying on linker flags, so the dylib path is hardcoded.  Second, this is just osx, @urschrei you're right that windows/linux support is a whole other can of worms. Lastly, I looked at the brew recipe and there are various data sets associated with a proj4 release. Definitely it would be hard to include those in a crate.  Oh and there was one mysterious failing test after linking to this proj: https://gist.github.com/svevang/789e76d94abcd656290c9ba466ca694a

Maybe the initial easy solution here is just to print a helpful error message.

**Comment by guidorice** [comment]
@svevang @urschrei  coincidentally I posted about this same issue on the Users forum. (I missed this issue somehow until today).

https://users.rust-lang.org/t/how-to-configure-rustc-link-lib-on-os-x-libproj-a-proj4/39617

I have installed Proj via Homebrew on OS X, and was trying to get the right build settings. See the response from Kornel, which has a link to a useful article.

**Comment by urschrei** [comment]
Ah, that’s useful @guidorice. I’ll see if I can figure out how to incorporate it. I may try to enlist your help in testing a fix if that’s OK.

**Comment by urschrei** [comment]
@guidorice I've pushed the [pkg-config](https://github.com/georust/proj-sys/tree/pkg_config) branch, which has a preliminary attempt at discovering the lib path and adding it to the `link-lib` search path. Can you clone it and try a `cargo build`?

**Comment by guidorice** [comment]
@urschrei I did some testing, and tweaked it a little and still could not get `cargo build` to work but here is more info for you. Thank so much for checking into this, glad to help as much as I can, but let me know what you think.

(using `brew install pkg-config; brew install proj` on OS X 10.15)

- Using proj v7, which is installed by `brew install proj`, the build script fails with:

```
> cargo build
   Compiling proj-sys v0.13.0 (/Users/alex/repos/proj-sys)
error: failed to run custom build command for `proj-sys v0.13.0 (/Users/alex/repos/proj-sys)`

Caused by:
  process didn't exit successfully: `/Users/alex/repos/proj-sys/target/debug/build/proj-sys-953401ace3b9892d/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"proj\" \"proj >= 7.0.0\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Variable \'datarootdir\' not defined in \'/usr/local/lib/pkgconfig/proj.pc\'\n" } }', build.rs:12:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I verified the `pkg-config` command with those arguments does fail because of undefined `datarootdir`. It sounds like this a known issue, as it was mentioned in #9 .

Next I tried installing proj v6 instead (just to try to force the build script to run) This involves searching through the homebrew git log for the last commit referencing a v6

```bash
brew uninstall proj
brew unlink proj
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/31ae0e5eb7d3d63cdc5047ee779a4c43286c8f65/Formula/proj.rb
```

Edited your build.rs

```
-        .atleast_version("7.0.0")
+        .atleast_version("6.3.0")
```

Try cargo build again
```
> cargo build
   Compiling proj-sys v0.13.0 (/Users/alex/repos/proj-sys)
error: failed to run custom build command for `proj-sys v0.13.0 (/Users/alex/repos/proj-sys)`

Caused by:
  process didn't exit successfully: `/Users/alex/repos/proj-sys/target/debug/build/proj-sys-953401ace3b9892d/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/local/Cellar/proj/6.3.1/lib
cargo:rustc-link-lib=proj
cargo:rustc-link-search=native="/usr/local/Cellar/proj/6.3.1/lib"
cargo:rustc-link-lib=proj

--- stderr
wrapper.h:1:10: fatal error: 'proj.h' file not found
wrapper.h:1:10: fatal error: 'proj.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', build.rs:24:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So the good news is it is finding the proj library and the link path. However, it needs the header files. I inspected the `pk` config struct and the path there in 

` println!("{:?}", pk.include_paths[0]);` ->` "/usr/local/Cellar/proj/6.3.1/include"`

Somehow I guess bindgen needs to be told about the path?

https://stackoverflow.com/questions/42741815/setting-the-include-path-with-bindgen#43105582

**Comment by urschrei** [comment]
Argh I forgot the datarootdir issue. I’ve got a working one for Proj 7.0.0 — hang on.

**Comment by urschrei** [comment]
@guidorice OK, so if you:

1. Reinstall PROJ 7.0.0 from Homebrew
2. Replace the contents of `/usr/local/lib/pkgconfig/proj.pc` with https://gist.github.com/urschrei/2a515c4a1b168579698b56990b8fcb58
3. pull the `pkg_config` branch to get an updated `build.rs`
4. Try  `cargo build` again.

**Comment by guidorice** [comment]
@urschrei I did the above steps, and still got an error, but solved it with 1 change to the `clang_arg` which I think needs `-I`.

```
> cargo build
   Compiling proj-sys v0.13.0 (/Users/alex/repos/proj-sys)
error: failed to run custom build command for `proj-sys v0.13.0 (/Users/alex/repos/proj-sys)`

Caused by:
  process didn't exit successfully: `/Users/alex/repos/proj-sys/target/debug/build/proj-sys-953401ace3b9892d/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/local/Cellar/proj/7.0.0/lib
cargo:rustc-link-lib=proj
cargo:rustc-link-search=native="/usr/local/Cellar/proj/7.0.0/lib"
cargo:rustc-link-lib=proj
"/usr/local/Cellar/proj/7.0.0/include"

--- stderr
warning: /usr/local/Cellar/proj/7.0.0/include: 'linker' input unused [-Wunused-command-line-argument]
wrapper.h:1:10: fatal error: 'proj.h' file not found
warning: /usr/local/Cellar/proj/7.0.0/include: 'linker' input unused [-Wunused-command-line-argument], err: false
wrapper.h:1:10: fatal error: 'proj.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', build.rs:25:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
(edit build.rs)

```
> git diff
diff --git a/build.rs b/build.rs
index 175d4ce..494bac5 100644
--- a/build.rs
+++ b/build.rs
@@ -23,7 +23,7 @@ fn main() {
     // to bindgen, and lets you build up options for
     // the resulting bindings.
     let bindings = bindgen::Builder::default()
-        .clang_arg(include_path)
+        .clang_arg(format!("-I{}", include_path))
         .trust_clang_mangling(false)
         .blacklist_type("max_align_t")
         // The input header we would like to generate
```

Now `cargo build` and `cargo test` succeed. 🎉

**Comment by urschrei** [comment]
Fantastic. I need to do a bit more research to see how the changes interact with Linux, but I’ll get a release out as soon as I can.

**Comment by urschrei** [comment]
OK! Homebrew has [merged in my fixes](https://github.com/Homebrew/homebrew-core/pull/51902) to the PROJ formula, so `pkgconfig` now runs correctly (and is gated) on macOS. We're now testing macOS on CI (once #13 merges), and everything's looking rosy, so I'll shortly be cutting the 0.15.0 release, and cutting a new https://github.com/georust/proj version that uses it.

Thanks for being patient, and to @guidorice for finding the fix!

**Comment by guidorice** [comment]
@urschrei this is awesome! thanks
